# Generated by Django 5.2.1 on 2025-06-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_date_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_shipped',
            new_name='shipped',
        ),
    ]
